// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjaYRZe8-tl8kBGuT9HYlNhZFSAKqiBA',
    appId: '1:205803264064:web:67f5def282037f40e127a5',
    messagingSenderId: '205803264064',
    projectId: 'personal-finance-4d693',
    authDomain: 'personal-finance-4d693.firebaseapp.com',
    storageBucket: 'personal-finance-4d693.firebasestorage.app',
    measurementId: 'G-4SWKWPF5ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ7A3-NuDmG1KkkhgRLrzmKgD-PMHxkwU',
    appId: '1:205803264064:android:8ad47a99f907a471e127a5',
    messagingSenderId: '205803264064',
    projectId: 'personal-finance-4d693',
    storageBucket: 'personal-finance-4d693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghGuMpFGGSo1F9nxm3N8jUEybRE7SUi8',
    appId: '1:205803264064:ios:057e318da4180bafe127a5',
    messagingSenderId: '205803264064',
    projectId: 'personal-finance-4d693',
    storageBucket: 'personal-finance-4d693.firebasestorage.app',
    iosBundleId: 'com.addsdev.personalFinanceApp',
  );
}
